### ISSUE TITLE
Stackline crash

### ISSUE THREAD

**Issue by arnaudjuracek** [AdamWagner/stackline#46] opened 2020-10-23 19:55 UTC
Hi, and thank you for your work on this project.

Stackline crashes repeatedly on my Yabai setup when working with stacks, giving me this error log:
```
2020-10-23 21:42:28: 21:42:28 ERROR:   LuaSkin: hs.timer callback error: ...rs/RNO/.hammerspoon/stackline/stackline/stackmanager.lua:66: attempt to index a nil value (field 'integer index')
stack traceback:
  ...rs/RNO/.hammerspoon/stackline/stackline/stackmanager.lua:66: in local 'fn'
  ...on.app/Contents/Resources/extensions/hs/fnutils/init.lua:57: in function 'hs.fnutils.map'
  ...rs/RNO/.hammerspoon/stackline/stackline/stackmanager.lua:64: in function 'stackline.stackline.stackmanager.getSummary'
  /Users/RNO/.hammerspoon/stackline/stackline/query.lua:129: in function 'stackline.stackline.query.windowsCurrentSpace'
  ...rs/RNO/.hammerspoon/stackline/stackline/stackmanager.lua:14: in function 'stackline.stackline.stackmanager.update'
  /Users/RNO/.hammerspoon/stackline/stackline/stackline.lua:42: in function </Users/RNO/.hammerspoon/stackline/stackline/stackline.lua:41>
```
I am running on Stackline on macOS `10.14.6 (18G6032)`.
Latest commit on my local repo is c93a0bd so I am currently up-to-date.

Sorry for not being more precise on the title of this issue, I'm quite new to Yabai, Hammerspoon and Stackline (in fact it is thanks to your project that I'm trying Yabai).

**Comment by kerryj89** [comment] 2020-11-07 16:51
Same here.

**Comment by AdamWagner** [comment] 2020-11-07 17:55
Well, that's no good. 
Thanks for the report + corroboration @arnaudjuracek & @kerryj89.

Unfortunately, I don't experience that error, even when using stackline for long periods. I can see that the error is caused by attempting to index a null list of `windows` in the `getSummary()` method… but `windows` should _never_ be null there. 

I _could_ just wrap these operations in the lua version of `try/catch`, but I don't think that would actually solve the problem, but just move it up a level, since the update method requires a summary of the current state. 

I'm sorry for pulling out the "need more info" card…  but unfortunately, I do :-)

---

>Stackline crashes repeatedly on my Yabai setup when working with stacks

Can you share a little more detail about "…repeatedly…"? 
Do you experience the crash + error message:

- Immediately at startup?
- Always/sometimes after executing a particular action (focusing stacked window, focusing _any_ window,  adding new window, resizing windows, changing spaces, etc)? 
- Seemingly randomly (that is, the error occurs when you're not interacting with your computer)

My guess is that the error occurs after some set of the focus/resize/add/remove window events above. It would be helpful but not crucial to know exactly which actions cause the error.

---

>…giving me this error log

- Is the error log always pretty much the same, or does it vary?

**Comment by arnaudjuracek** [comment] 2020-11-07 19:37
Thanks for your response. 

Note that as Stackline was pretty much always crashed on my config when needed, I gained the habit of not using it at all, and I am now using Yabai's stacks without Stackline.

That being said, here are more informations:

---
> - Is the error log always pretty much the same, or does it vary?

Nope, always pretty much the same.

---
> Can you share a little more detail about "…repeatedly…"?
> Do you experience the crash + error message:
>
> - Immediately at startup?
> - Always/sometimes after executing a particular action (focusing stacked window, focusing any window, adding new window, resizing windows, changing spaces, etc)?
> - Seemingly randomly (that is, the error occurs when you're not interacting with your computer)

To be honest I was quite embarrassed to open this issue without being able to provide much more informations, but the fact is that I have absolutely no clue on what causes the crashes. They seemed pretty random to me, and at least I can say that I did not identify a specific setup or series of actions to reproduce the crash.

My usual opened apps are :

###### Managed by yabai
- iTerm2
- Sublime Text 3
- Finder
- Chrome / Chromium

###### Unmanaged by yabai
- Mail.app
- Slack
- Spotify

I also have a bunch of menubar apps hidden via Bartender, but I do not know if this can be related to our problem.

---
Unfortunately I did not use Stackline enough to give you much more informations… but @kerryj89 may be more helpful.

Cheers.

**Comment by kerryj89** [comment] 2020-11-08 04:07
@AdamWagner Upon reloading config in Hammerspoon I get the attached error (eventually I get the same "nil value" messages also).  Posting it here since OP is no longer using this tool.  Do you have any ideas what it could be?  FYI I followed the instructions on https://github.com/AdamWagner/stackline yesterday.

Hammerspoon 0.9.81
Yabai 3.3.0 with latest scripting additions
OSX Catalina 10.15.7

What Hammerspoon version are you on?

The stacking indicators work but clicking on them does not change them for me even though the config says the "clickToFocus" is enabled.  I think the erroring is maybe preventing that function.  Any help is appreciated!

```
2020-11-07 21:46:27: -- Lazy extension loading enabled
2020-11-07 21:46:27: -- Loading ~/.hammerspoon/init.lua
2020-11-07 21:46:27: -- Loading extension: logger
2020-11-07 21:46:27: 21:46:27      utils: Loading module
2020-11-07 21:46:27: -- Loading extension: fnutils
2020-11-07 21:46:27: -- Loading extension: window
2020-11-07 21:46:27: -- Loading extensions: window.filter
2020-11-07 21:46:27: -- Loading extension: timer
2020-11-07 21:46:27: -- Loading extension: eventtap
2020-11-07 21:46:27:           stackline: Loading module
2020-11-07 21:46:27:          sline.conf: Loading module
2020-11-07 21:46:27: -- Loading extension: spaces
2020-11-07 21:46:27:           stackline: starting stackline
2020-11-07 21:46:28: 



2020-11-07 21:46:28: ========================================
2020-11-07 21:46:28: T1	==========
2020-11-07 21:46:28: ========================================
2020-11-07 21:46:28: -- Loading extension: inspect
2020-11-07 21:46:28: {
  advanced = {
    maxRefreshRate = 0.3
  },
  appearance = {
    alpha = 1,
    color = {
      white = 0.9
    },
    dimmer = 2.5,
    fadeDuration = 0.2,
    iconDimmer = 1.1,
    iconPadding = 4,
    offset = {
      x = 4,
      y = 2
    },
    pillThinness = 6,
    radius = 3,
    shouldFade = true,
    showIcons = false,
    size = 32,
    vertSpacing = 1.2
  },
  features = {
    clickToFocus = true,
    dynamicLuminosity = "not_implemented",
    fzyFrameDetect = {
      enabled = true,
      fuzzFactor = 30
    },
    hsBugWorkaround = true,
    winTitles = "not_implemented"
  },
  paths = {
    getStackIdxs = "/Users/kjohnson/.hammerspoon/stackline/bin/yabai-get-stack-idx",
    jq = "/usr/local/bin/jq",
    yabai = "/usr/local/bin/yabai"
  }
}
2020-11-07 21:46:28: 



2020-11-07 21:46:28: ========================================
2020-11-07 21:46:28: T2	==========
2020-11-07 21:46:28: ========================================
2020-11-07 21:46:28: {}
2020-11-07 21:46:28: 21:46:28 sline.conf: Initializing configmanager…
2020-11-07 21:46:28:          sline.conf: schemaType: dynamicLuminosity
2020-11-07 21:46:28:          sline.conf: schemaType: boolean
2020-11-07 21:46:28:          sline.conf: schemaType: winTitles
2020-11-07 21:46:28:          sline.conf: schemaType: boolean
2020-11-07 21:46:28:          sline.conf: schemaType: number
2020-11-07 21:46:28:          sline.conf: schemaType: boolean
2020-11-07 21:46:28:          sline.conf: schemaType: 0.3
2020-11-07 21:46:28:          sline.conf: schemaType: number
2020-11-07 21:46:28:          sline.conf: schemaType: boolean
2020-11-07 21:46:28:          sline.conf: schemaType: number
2020-11-07 21:46:28:          sline.conf: schemaType: number
2020-11-07 21:46:28:          sline.conf: schemaType: number
2020-11-07 21:46:28:          sline.conf: schemaType: boolean
2020-11-07 21:46:28:          sline.conf: schemaType: number
2020-11-07 21:46:28:          sline.conf: schemaType: number
2020-11-07 21:46:28:          sline.conf: schemaType: number
2020-11-07 21:46:28:          sline.conf: schemaType: number
2020-11-07 21:46:28:          sline.conf: schemaType: color
2020-11-07 21:46:28:          sline.conf: schemaType: number
2020-11-07 21:46:28:          sline.conf: schemaType: number
2020-11-07 21:46:28:          sline.conf: schemaType: number
2020-11-07 21:46:28:          sline.conf: schemaType: string
2020-11-07 21:46:28:          sline.conf: schemaType: string
2020-11-07 21:46:28:          sline.conf: schemaType: string
2020-11-07 21:46:28:          sline.conf: Not validating:  nil
2020-11-07 21:46:28:          sline.conf: ✓ Conf validated successfully
2020-11-07 21:46:28: -- Loading extension: ipc
2020-11-07 21:46:28: -- Loading extension: task
2020-11-07 21:46:28:           stackline: FEAT: ClickTracker starting
2020-11-07 21:46:28:           stackline: starting stackline
2020-11-07 21:46:28: 



2020-11-07 21:46:28: ========================================
2020-11-07 21:46:28: T1	==========
2020-11-07 21:46:28: ========================================
2020-11-07 21:46:28: {
  advanced = {
    maxRefreshRate = 0.3
  },
  appearance = {
    alpha = 1,
    color = {
      white = 0.9
    },
    dimmer = 2.5,
    fadeDuration = 0.2,
    iconDimmer = 1.1,
    iconPadding = 4,
    offset = {
      x = 4,
      y = 2
    },
    pillThinness = 6,
    radius = 3,
    shouldFade = true,
    showIcons = false,
    size = 32,
    vertSpacing = 1.2
  },
  features = {
    clickToFocus = true,
    dynamicLuminosity = "not_implemented",
    fzyFrameDetect = {
      enabled = true,
      fuzzFactor = 30
    },
    hsBugWorkaround = true,
    winTitles = "not_implemented"
  },
  paths = {
    getStackIdxs = "/Users/kjohnson/.hammerspoon/stackline/bin/yabai-get-stack-idx",
    jq = "/usr/local/bin/jq",
    yabai = "/usr/local/bin/yabai"
  }
}
2020-11-07 21:46:28: 



2020-11-07 21:46:28: ========================================
2020-11-07 21:46:28: T2	==========
2020-11-07 21:46:28: ========================================
2020-11-07 21:46:28: {}
2020-11-07 21:46:28:          sline.conf: Initializing configmanager…
2020-11-07 21:46:28:          sline.conf: schemaType: dynamicLuminosity
2020-11-07 21:46:28:          sline.conf: schemaType: boolean
2020-11-07 21:46:28:          sline.conf: schemaType: winTitles
2020-11-07 21:46:28:          sline.conf: schemaType: boolean
2020-11-07 21:46:28:          sline.conf: schemaType: number
2020-11-07 21:46:28:          sline.conf: schemaType: boolean
2020-11-07 21:46:28:          sline.conf: schemaType: 0.3
2020-11-07 21:46:28:          sline.conf: schemaType: number
2020-11-07 21:46:28:          sline.conf: schemaType: boolean
2020-11-07 21:46:28:          sline.conf: schemaType: number
2020-11-07 21:46:28:          sline.conf: schemaType: number
2020-11-07 21:46:28:          sline.conf: schemaType: number
2020-11-07 21:46:28:          sline.conf: schemaType: boolean
2020-11-07 21:46:28:          sline.conf: schemaType: number
2020-11-07 21:46:28:          sline.conf: schemaType: number
2020-11-07 21:46:28:          sline.conf: schemaType: number
2020-11-07 21:46:28:          sline.conf: schemaType: number
2020-11-07 21:46:28:          sline.conf: schemaType: color
2020-11-07 21:46:28:          sline.conf: schemaType: number
2020-11-07 21:46:28:          sline.conf: schemaType: number
2020-11-07 21:46:28:          sline.conf: schemaType: number
2020-11-07 21:46:28:          sline.conf: schemaType: string
2020-11-07 21:46:28:          sline.conf: schemaType: string
2020-11-07 21:46:28:          sline.conf: schemaType: string
2020-11-07 21:46:28:          sline.conf: Not validating:  nil
2020-11-07 21:46:28:          sline.conf: ✓ Conf validated successfully
2020-11-07 21:46:28: *** ERROR: ...hnson/.hammerspoon/stackline/stackline/configManager.lua:135: local port name already in use
stack traceback:
	[C]: in function 'hs.ipc.internal.localPort'
	...hnson/.hammerspoon/stackline/stackline/configManager.lua:135: in function 'stackline.stackline.configManager.init'
	.../kjohnson/.hammerspoon/stackline/stackline/stackline.lua:29: in function 'stackline.stackline.stackline.init'
	/Users/kjohnson/.hammerspoon/init.lua:4: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:702: in function 'hs._coresetup.setup'
	(...tail calls...)
2020-11-07 21:46:28: -- Loading extension: json
2020-11-07 21:46:36: -- Loading extension: geometry
2020-11-07 21:47:05: -- Loading extension: canvas
2020-11-07 21:47:09: num stacks changed
2020-11-07 21:47:15: num windows changed
2020-11-07 21:47:17: num windows changed
2020-11-07 21:47:18: num windows changed
2020-11-07 21:47:28: position changed
2020-11-07 21:47:40: Should not redraw.
```

**Comment by MrZeroo00** [comment] 2020-11-26 10:55
Same here. I ended up in the same situation as @arnaudjuracek.
> Note that as Stackline was pretty much always crashed on my config when needed, I gained the habit of not using it at all, and I am now using Yabai's stacks without Stackline.

**Comment by AdamWagner** [comment] 2020-11-28 17:02
>To be honest I was quite embarrassed to open this issue without being able to provide much more informations, but the fact is that I have absolutely no clue on what causes the crashes. They seemed pretty random to me, and at least I can say that I did not identify a specific setup or series of actions to reproduce the crash.

@arnaudjuracek Thanks for reporting the issue anyway, and following up with more detail! Clearly others are running into the same problem, so I need to figure out what's going on here.

The last three weekends I've been pretty heads-down working on writing Hammerspoon mocks and tests for Stackline. Today I'm going to just focus on trying to reproducing this crash and then writing a test for it 👍

**Comment by AdamWagner** [comment] 2020-11-28 17:05
@kerryj89 

Interesting! The `local port name already in use` error is probably different, but may be useful clue if it always results in the `nil value` error. Thanks!

@MrZeroo00 and @arnaudjuracek – I totally understand why you would stop using use a tool that consistently crashes. I'm sorry that stackline hasn't worked out for you. It I'll Update this thread if I identify / resolve the issue.

**Comment by AdamWagner** [comment] 2020-11-28 21:34
@kerryj89 Some good news, I think:

I was able to reproduce `2020-11-07 21:46:28: *** ERROR: configManager.lua:135: local port name already in use` by calling `stackline:init()` when it had already been initialized. My guess is that `stackline:init()` is being called twice. Note that this should only be called once from your `~/.hammerspoon/init.lua` file. If you find a call to `stackline:init()` from within the stackline module itself, then you're running an old version ;-) 

I'm now guarding against this in the init method:

```lua
    if stackline.manager then
        -- guard against re-initializtion https://github.com/AdamWagner/stackline/issues/46#issuecomment-723527826
        return print('stackline already initialized')
    end
```

---

Also, I've added debug info to `Stackmanager:getSummary()` that should help shed light on the bug originally reported in this thread.

You can see the changes here: https://github.com/AdamWagner/stackline/blob/fix/nil-windows-in-get-summary/stackline/stackmanager.lua#L64

---

So, if you're willing to pull down the branch with these changes (https://github.com/AdamWagner/stackline/tree/fix/nil-windows-in-get-summary), then we should see:

1. The `local port name already in use` crash should be fixed (this should also fix the problems with clicking indicators to focus the window)
2. If you encounter the nil value in `getSummary()`, we'll have extra debug info to show the way!

---

BTW, thanks for sharing your system specs. I'm using:

Hammerspoon 0.9.82 (though I just upgraded today and was running 0.9.8.1  before that)
yabai-v3.3.4 (I'm running HEAD. I would be surprised if this was a factor)
OSX Catalina 10.15.7

**Comment by kerryj89** [comment] 2020-11-29 09:34
Hi Adam,

I deleted `~/.hammerspoon` and ran `git clone -b fix/nil-windows-in-get-summary https://github.com/AdamWagner/stackline.git ~/.hammerspoon/stackline` and followed the setup instructions carefully again.

It loads up but the icons do not follow the stacked windows and are not clickable.  My hammerspoon announces this:

```
2020-11-29 03:32:16: 03:32:16 ERROR:   LuaSkin: hs.timer callback error: ...ohnson/.hammerspoon/stackline/stackline/stackmanager.lua:81: attempt to index a nil value (field 'integer index')
stack traceback:
	...ohnson/.hammerspoon/stackline/stackline/stackmanager.lua:81: in local 'fn'
	...on.app/Contents/Resources/extensions/hs/fnutils/init.lua:57: in function 'hs.fnutils.map'
	...ohnson/.hammerspoon/stackline/stackline/stackmanager.lua:75: in function 'stackline.stackline.stackmanager.getSummary'
	/Users/kjohnson/.hammerspoon/stackline/stackline/query.lua:129: in function 'stackline.stackline.query.windowsCurrentSpace'
	...ohnson/.hammerspoon/stackline/stackline/stackmanager.lua:14: in function 'stackline.stackline.stackmanager.update'
	.../kjohnson/.hammerspoon/stackline/stackline/stackline.lua:47: in function <.../kjohnson/.hammerspoon/stackline/stackline/stackline.lua:46>
2020-11-29 03:32:18: 03:32:18 ERROR:   LuaSkin: hs.timer callback error: ...ohnson/.hammerspoon/stackline/stackline/stackmanager.lua:81: attempt to index a nil value (field 'integer index')
stack traceback:
	...ohnson/.hammerspoon/stackline/stackline/stackmanager.lua:81: in local 'fn'
	...on.app/Contents/Resources/extensions/hs/fnutils/init.lua:57: in function 'hs.fnutils.map'
	...ohnson/.hammerspoon/stackline/stackline/stackmanager.lua:75: in function 'stackline.stackline.stackmanager.getSummary'
	/Users/kjohnson/.hammerspoon/stackline/stackline/query.lua:129: in function 'stackline.stackline.query.windowsCurrentSpace'
	...ohnson/.hammerspoon/stackline/stackline/stackmanager.lua:14: in function 'stackline.stackline.stackmanager.update'
	.../kjohnson/.hammerspoon/stackline/stackline/stackline.lua:47: in function <.../kjohnson/.hammerspoon/stackline/stackline/stackline.lua:46>
2020-11-29 03:32:19: 03:32:19 ERROR:   LuaSkin: hs.timer callback error: ...ohnson/.hammerspoon/stackline/stackline/stackmanager.lua:81: attempt to index a nil value (field 'integer index')
stack traceback:
	...ohnson/.hammerspoon/stackline/stackline/stackmanager.lua:81: in local 'fn'
	...on.app/Contents/Resources/extensions/hs/fnutils/init.lua:57: in function 'hs.fnutils.map'
	...ohnson/.hammerspoon/stackline/stackline/stackmanager.lua:75: in function 'stackline.stackline.stackmanager.getSummary'
	/Users/kjohnson/.hammerspoon/stackline/stackline/query.lua:129: in function 'stackline.stackline.query.windowsCurrentSpace'
	...ohnson/.hammerspoon/stackline/stackline/stackmanager.lua:14: in function 'stackline.stackline.stackmanager.update'
	.../kjohnson/.hammerspoon/stackline/stackline/stackline.lua:47: in function <.../kjohnson/.hammerspoon/stackline/stackline/stackline.lua:46>
2020-11-29 03:32:51: 03:32:51 ERROR:   LuaSkin: hs.timer callback error: ...ohnson/.hammerspoon/stackline/stackline/stackmanager.lua:81: attempt to index a nil value (field 'integer index')
stack traceback:
	...ohnson/.hammerspoon/stackline/stackline/stackmanager.lua:81: in local 'fn'
	...on.app/Contents/Resources/extensions/hs/fnutils/init.lua:57: in function 'hs.fnutils.map'
	...ohnson/.hammerspoon/stackline/stackline/stackmanager.lua:75: in function 'stackline.stackline.stackmanager.getSummary'
	/Users/kjohnson/.hammerspoon/stackline/stackline/query.lua:129: in function 'stackline.stackline.query.windowsCurrentSpace'
	...ohnson/.hammerspoon/stackline/stackline/stackmanager.lua:14: in function 'stackline.stackline.stackmanager.update'
	.../kjohnson/.hammerspoon/stackline/stackline/stackline.lua:47: in function <.../kjohnson/.hammerspoon/stackline/stackline/stackline.lua:46>
```

Thanks for trying to fix the issue!

**Comment by antoniom13** [comment] 2020-12-31 16:07
Thank for maintaining this and trying to get this solved.  I'm on the same boat as @kerryj89.

These are the current versions running:

`hammerspoon` Version 0.9.82 (5614)
`yabai` v3.3.6
`stackline` master on 8c1533e

In order to replicate:

- All services stopped
- Start hammerspoon
- Start yabai

The following error is thrown as soon as yabai starts:

```bash
2020-12-31 10:56:14: 10:56:14 ERROR:   LuaSkin: hs.task callback: /Users/antonio/.hammerspoon/stackline/stackline/query.lua:13: attempt to call a nil value (upvalue 'onSuccess')
stack traceback:
	/Users/antonio/.hammerspoon/stackline/stackline/query.lua:13: in function </Users/antonio/.hammerspoon/stackline/stackline/query.lua:9>```

This is followed by

```bash
2020-12-31 10:58:47: 10:58:47 ERROR:   LuaSkin: hs.timer callback error: ...ntonio/.hammerspoon/stackline/stackline/stackmanager.lua:66: attempt to index a nil value (field 'integer index')
stack traceback:
	...ntonio/.hammerspoon/stackline/stackline/stackmanager.lua:66: in local 'fn'
	...on.app/Contents/Resources/extensions/hs/fnutils/init.lua:57: in function 'stackline.lib.utils.map'
	...ntonio/.hammerspoon/stackline/stackline/stackmanager.lua:64: in function 'stackline.stackline.stackmanager.getSummary'
	/Users/antonio/.hammerspoon/stackline/stackline/query.lua:129: in function 'stackline.stackline.query.windowsCurrentSpace'
	...ntonio/.hammerspoon/stackline/stackline/stackmanager.lua:14: in function 'stackline.stackline.stackmanager.update'
	...s/antonio/.hammerspoon/stackline/stackline/stackline.lua:47: in function <...s/antonio/.hammerspoon/stackline/stackline/stackline.lua:46>```

I'm happy to troubleshoot and help where needed.

**Comment by shepherdjerred** [comment] 2021-01-10 20:08
I'm also seeing this issue on two machines, an Intel MacBook and an M1 Mac, both on Big Sur.

hammerspoon: 0.9.82 (5614)
yabai: v3.3.6
stackline: 8c1533ea71e9af3315edb889a6a44e7cc5723f16

**Closed** 2021-06-06 11:13 UTC
Labels: bug, potentially-fixed

**Comment by ninjalu** [comment] 2022-01-03 17:22
> Thanks for your response.
> 
> Note that as Stackline was pretty much always crashed on my config when needed, I gained the habit of not using it at all, and I am now using Yabai's stacks without Stackline.
> 
Could you possibly provide instructions for how to use Yabai's stacks without Stackline? I haven't been able to do that reading on docs and repos.. :(.. Many thanks!
