### ISSUE TITLE
Error message in hammerspoon console and no icons shown [/bin/dash only available on Catalina+]

### ISSUE THREAD

**Issue by jayson** [AdamWagner/stackline#31] opened 2020-08-28 21:02 UTC
I just installed this with the recommended init.lua contents and all the dependencies. My hammerspoon console keeps showing this error: "Warning: LuaSkin: hs.task:launch() Unable to launch hs.task process: launch path not accessible"

Full hammerspoon log:

> 2020-08-28 16:59:56: Welcome to the Hammerspoon Console!

> You can run any Lua code in here.
> 
> 2020-08-28 16:59:56: -- Lazy extension loading enabled
> 2020-08-28 16:59:56: -- Loading ~/.hammerspoon/init.lua
> 2020-08-28 16:59:56: -- Loading extension: settings
> 2020-08-28 16:59:56: org.hammerspoon.Hammerspoon
> 2020-08-28 16:59:56: -- Loading extension: ipc
> 2020-08-28 16:59:56: -- Loading extension: fnutils
> 2020-08-28 16:59:56: -- Loading extension: window
> 2020-08-28 16:59:56: -- Loading extension: uielement
> 2020-08-28 16:59:56: -- Loading extensions: window.filter
> 2020-08-28 16:59:56: -- Loading extension: timer
> 2020-08-28 16:59:56: -- Loading extension: spaces
> 2020-08-28 16:59:56: -- Loading extension: task
> 2020-08-28 16:59:56: 16:59:56 ** Warning:   LuaSkin: hs.task:launch() Unable to launch hs.task process: launch path not accessible
> 2020-08-28 16:59:56: -- Done.
> 2020-08-28 17:00:01: 17:00:01 ** Warning:   wfilter: No accessibility access to app UÌbersicht Networking (no watcher pid)
> 2020-08-28 17:00:01: 17:00:01 ** Warning:   wfilter: No accessibility access to app Discord Helper (Renderer) (no watcher pid)
> 2020-08-28 17:00:01: 17:00:01 ** Warning:   wfilter: No accessibility access to app FirefoxCP Web Content (no watcher pid)
> 2020-08-28 17:00:01: 17:00:01 ** Warning:   wfilter: No accessibility access to app FirefoxCP WebExtensions (no watcher pid)
> 2020-08-28 17:00:01: 17:00:01 ** Warning:   wfilter: No accessibility access to app FirefoxCP RDD Process (no watcher pid)
> 2020-08-28 17:00:01: 17:00:01 ** Warning:   wfilter: No accessibility access to app com.apple.hiservices-xpcservice (no watcher pid)
> 2020-08-28 17:00:11: 17:00:11 ** Warning:   LuaSkin: hs.task:launch() Unable to launch hs.task process: launch path not accessible
>

**Comment by jayson** [comment] 2020-08-29 01:11
I looked further into the stackline code and it is trying to execute:
```
 hs.task.new("/bin/dash", function(_code, stdout, _stderr)```

Which is not a binary on my machine. Is this a dependency that isn't listed?

**Comment by jayson** [comment] 2020-08-29 01:13
Oh wow that is debian shell. Not sure why you would use that over bash for something that is supposed to run on mac os. I changed it to bin/sh and no icons still appear. Please let me know what else I can do to debug this

**Comment by AdamWagner** [comment] 2020-09-01 01:18
@jayson I'm sorry that you ran into this. Are you running macOS High Sierra or older?

>Probably not coincidentally, Apple added the dash shell in Catalina. The Debian Almquist Shell (dash) is a minimal implementation of the Posix sh standard and commonly used on other UNIX and Unix-like systems as a stand-in for sh. [[src](https://scriptingosx.com/2020/06/about-bash-zsh-sh-and-dash-in-macos-catalina-and-beyond/)]


I used the dash shell because a) I [mistakenly] thought it was installed by default on most macOS versions, not just Catalina and b) because `dash` is famous for its fast startup  time and I wanted stackline to be as zippy as possible. The fact that it caused an error for you probably means we should just change it to `/bin/sh`. 

Since I haven't tested with this `/bin/sh` (and since it sounds like I'm running a different version of macOS than you are), I don't have a quick answer to why it's still not working for you. I'll try to do some testing this week and let you know. If you're able to share any additional info from the Hammerspoon console, that would help.

**Comment by AdamWagner** [comment] 2020-09-01 01:46
@jayson Can you pull from master and try again?

`/bin/dash` was used in one other place, too – the shell script that queries stack index from `yabai`. That's a tricky one because no error appears in the Hammerspoon console.

See changes in https://github.com/AdamWagner/stackline/commit/4bd8dc9eeceddfae76cfd24eb454e5e8a09264b8

… I replace both references to `/bin/dash` with `/bin/sh` which is what I should have done in the first place.

🖐

**Comment by AdamWagner** [comment] 2020-09-01 23:32
Closed by https://github.com/AdamWagner/stackline/commit/4bd8dc9eeceddfae76cfd24eb454e5e8a09264b8

**Closed by AdamWagner** 2020-09-01 23:32 UTC
Labels: bug

**Comment by jayson** [comment] 2020-09-02 15:33
Thank you. I will give it another try today

**Comment by jayson** [comment] 2020-09-02 15:35
I now get a very different error:

```2020-09-02 11:34:34: Welcome to the Hammerspoon Console!
You can run any Lua code in here.

2020-09-02 11:34:34: -- Lazy extension loading enabled
2020-09-02 11:34:34: -- Loading ~/.hammerspoon/init.lua
2020-09-02 11:34:34: -- Loading extension: settings
2020-09-02 11:34:34: org.hammerspoon.Hammerspoon
2020-09-02 11:34:34: -- Loading extension: fnutils
2020-09-02 11:34:34: -- Loading extension: ipc
2020-09-02 11:34:34: -- Loading extension: window
2020-09-02 11:34:34: -- Loading extension: uielement
2020-09-02 11:34:34: -- Loading extensions: window.filter
2020-09-02 11:34:36: -- Loading extension: timer
2020-09-02 11:34:36: -- Loading extension: spaces
2020-09-02 11:34:36: -- Done.
2020-09-02 11:34:36: 



2020-09-02 11:34:36: ========================================
2020-09-02 11:34:36: STARTING STACKLINE	==========
2020-09-02 11:34:36: ========================================
2020-09-02 11:34:36: ********
2020-09-02 11:34:36: 11:34:36 ERROR:   LuaSkin: hs.timer callback error: .../jpaul/.hammerspoon/stackline/stackline/stackmanager.lua:12: attempt to index a nil value (global 'stackline')
stack traceback:
	.../jpaul/.hammerspoon/stackline/stackline/stackmanager.lua:12: in function 'stackline.stackline.stackmanager.new'
	/Users/jpaul/.hammerspoon/stackline/stackline/stackline.lua:24: in function 'stackline.stackline.stackline.start'
	/Users/jpaul/.hammerspoon/stackline/stackline/stackline.lua:85: in upvalue 'actionFn'
	...poon.app/Contents/Resources/extensions/hs/timer/init.lua:147: in function <...poon.app/Contents/Resources/extensions/hs/timer/init.lua:145>
2020-09-02 11:34:36: ********
2020-09-02 11:34:40: 11:34:40 ** Warning:   wfilter: No accessibility access to app UÌbersicht Networking (no watcher pid)
2020-09-02 11:34:41: ********
2020-09-02 11:34:41: 11:34:41 ERROR:   LuaSkin: hs.application.watcher callback: /Users/jpaul/.hammerspoon/stackline/stackline/stackline.lua:38: attempt to index a nil value (field 'manager')
stack traceback:
	/Users/jpaul/.hammerspoon/stackline/stackline/stackline.lua:38: in function 'stackline.stackline.stackline.redrawWinIndicator'
	...n.app/Contents/Resources/extensions/hs/window/filter.lua:944: in upvalue 'emit'
	...n.app/Contents/Resources/extensions/hs/window/filter.lua:970: in method 'filterEmitEvent'
	...n.app/Contents/Resources/extensions/hs/window/filter.lua:1004: in method 'emitEvent'
	...n.app/Contents/Resources/extensions/hs/window/filter.lua:1096: in method 'unfocused'
	...n.app/Contents/Resources/extensions/hs/window/filter.lua:1285: in method 'deactivated'
	...n.app/Contents/Resources/extensions/hs/window/filter.lua:1270: in function <...n.app/Contents/Resources/extensions/hs/window/filter.lua:1267>
	(...tail calls...)
2020-09-02 11:34:41: ********
2020-09-02 11:34:41: 11:34:41 ** Warning:   wfilter: Hammerspoon (80629) is not registered yet
2020-09-02 11:34:41: 11:34:41 ** Warning:   wfilter: No accessibility access to app Discord Helper (Renderer) (no watcher pid)
2020-09-02 11:34:41: 11:34:41 ** Warning:   wfilter: No accessibility access to app FirefoxCP Web Content (no watcher pid)
2020-09-02 11:34:41: 11:34:41 ** Warning:   wfilter: No accessibility access to app FirefoxCP WebExtensions (no watcher pid)
2020-09-02 11:34:41: 11:34:41 ** Warning:   wfilter: No accessibility access to app FirefoxCP RDD Process (no watcher pid)
2020-09-02 11:34:41: 11:34:41 ** Warning:   wfilter: No accessibility access to app com.apple.hiservices-xpcservice (no watcher pid)
2020-09-02 11:34:42: ********
2020-09-02 11:34:42: 11:34:42 ERROR:   LuaSkin: hs.application.watcher callback: /Users/jpaul/.hammerspoon/stackline/stackline/stackline.lua:38: attempt to index a nil value (field 'manager')
stack traceback:
	/Users/jpaul/.hammerspoon/stackline/stackline/stackline.lua:38: in function 'stackline.stackline.stackline.redrawWinIndicator'
	...n.app/Contents/Resources/extensions/hs/window/filter.lua:944: in upvalue 'emit'
	...n.app/Contents/Resources/extensions/hs/window/filter.lua:970: in method 'filterEmitEvent'
	...n.app/Contents/Resources/extensions/hs/window/filter.lua:1004: in method 'emitEvent'
	...n.app/Contents/Resources/extensions/hs/window/filter.lua:1088: in method 'focused'
	...n.app/Contents/Resources/extensions/hs/window/filter.lua:1280: in function <...n.app/Contents/Resources/extensions/hs/window/filter.lua:1267>
	(...tail calls...)
2020-09-02 11:34:42: ********
2020-09-02 11:34:42: ********
2020-09-02 11:34:42: 11:34:42 ERROR:   LuaSkin: hs.application.watcher callback: /Users/jpaul/.hammerspoon/stackline/stackline/stackline.lua:38: attempt to index a nil value (field 'manager')
stack traceback:
	/Users/jpaul/.hammerspoon/stackline/stackline/stackline.lua:38: in function 'stackline.stackline.stackline.redrawWinIndicator'
	...n.app/Contents/Resources/extensions/hs/window/filter.lua:944: in upvalue 'emit'
	...n.app/Contents/Resources/extensions/hs/window/filter.lua:970: in method 'filterEmitEvent'
	...n.app/Contents/Resources/extensions/hs/window/filter.lua:1004: in method 'emitEvent'
	...n.app/Contents/Resources/extensions/hs/window/filter.lua:1096: in method 'unfocused'
	...n.app/Contents/Resources/extensions/hs/window/filter.lua:1285: in method 'deactivated'
	...n.app/Contents/Resources/extensions/hs/window/filter.lua:1270: in function <...n.app/Contents/Resources/extensions/hs/window/filter.lua:1267>
	(...tail calls...)
2020-09-02 11:34:42: ********
2020-09-02 11:34:42: ********
2020-09-02 11:34:42: 11:34:42 ERROR:   LuaSkin: hs.timer callback error: /Users/jpaul/.hammerspoon/stackline/stackline/stackline.lua:31: attempt to index a nil value (field 'manager')
stack traceback:
	/Users/jpaul/.hammerspoon/stackline/stackline/stackline.lua:31: in function </Users/jpaul/.hammerspoon/stackline/stackline/stackline.lua:28>
2020-09-02 11:34:42: ********
```

**Comment by jayson** [comment] 2020-09-02 15:39
I'm noticing a multiple monitor branch, perhaps I should be trying that

**Comment by AdamWagner** [comment] 2020-09-02 16:24
@jayson see https://github.com/AdamWagner/stackline/issues/34

**Comment by jayson** [comment] 2020-09-02 17:52
Thanks! I changed that and the error stopped but then I realized that this just doesn't work with iterm2. I was able to successfully stack with firefox and hammerspoon.

**Comment by AdamWagner** [comment] 2020-09-02 19:10
>realized that this just doesn't work with iterm2

I just reproduced. Looking at the window frame, I think that iterm2 constricts window size to even rows/columns or something, which breaks the "are window frames equal?" test that defines a stack.

See https://github.com/AdamWagner/stackline/issues/32

I think the solution is to fuzz the "are window frames equal?" check a bit (e.g., round frame to nearest 5 pts before comparison)

**Comment by jayson** [comment] 2020-09-02 19:17
Ah yes that would do it. iTerm 2 definitely messes with the size.

**Comment by AdamWagner** [comment] 2020-09-11 03:12
@jayson if you'd like to kick the tires of a potential fix, there's an open PR here: https://github.com/AdamWagner/stackline/pull/37
