### ISSUE TITLE
Stackline sometimes missing icons

### ISSUE THREAD

**Issue by alextremblay** [AdamWagner/stackline#44] opened 2020-09-28 14:47 UTC
Hello,

first off, thank you for making stackline :)

I've noticed a rather curious bug, where SOME app icons are missing. Ex:

<img width="693" alt="stackline-missing-icons" src="https://user-images.githubusercontent.com/23367954/94444620-82f72080-0174-11eb-9799-380120542ff3.png">

In this example, there are siz windows in this stack:
- chrome
- alacritty
- kitty
- alacritty (app icon missing)
- chrome
- kitty (app icon missing)

What's more interesting, is that if i navigate to those windows with `stack.next` and `stack.prev` selectors, the opacity of the rest of the stackline changes, as if i had moved focus away from the entire stack (ie. the indicator background for the last-focused window in the stack becomes 50% opaque, the rest transparent)

Tried with stackline ced44734397bae69aa89c410f274106042024fc0 and with latest version of master from this morning

running with yabai-v3.3.0 on MacOS Catalina

Please let me know if there's any additional information I can provide. Thank you!

**Comment by alextremblay** [comment] 2020-09-28 14:56
I also sometimes see this in the hammerspoon cosole:
```
2020-09-28 10:43:40: 10:43:40 ERROR:   LuaSkin: Unable to fetch element attribute NSAccessibilityFrontmostAttribute for: Alacritty
```
This log line only shows up the very first time i create an alacritty window in a given space. I'm not sure what to make of it

**Comment by AdamWagner** [comment] 2020-10-04 14:55
Great report, thanks @alextremblay . Every so often, I see this issue (with Chrome & Kitty specifically, in fact), but haven't been able to reproduce it reliably-enough to ensure that I've fixed it.

I'm pretty sure it's caused by small differences in the window frame dimensions of the windows that are missing icons (`stackline` identifies a stack as a group of windows that share identical window frames. See https://github.com/koekeishiya/yabai/issues/672 for a `yabai` FR that would enable `stackline` to abandon this flimsy heuristic). 

You can confirm ↑ by running `yabai -m query --windows --space | fx # (jq/jid/gron or whatever)` and manually comparing the frame sizes of the windows without icons. 

If this test confirms the issue (or you're just curious), you can try one of the two branches that have fuzzy frame matching:

1. [feature/fuzzy-stacked-win-detection](https://github.com/AdamWagner/stackline/tree/feature/fuzzy-stacked-win-detection) – this is a bit old, but has just the changes you'd need to test the hypothesis
2. [feature/configuration](https://github.com/AdamWagner/stackline/tree/feature/configuration) – this is built on top of ↑ and includes a major update to configuration (see [notes for details](https://github.com/AdamWagner/stackline/issues/33)). So, it's fun and shiny, but will probably require some fiddling / changes to how your initialize `stackline` in your main `init.lua` file.

---

>What's more interesting, is that if i navigate to those windows with stack.next and stack.prev selectors, the opacity of the rest of the stackline changes, as if i had moved focus away from the entire stack (ie. the indicator background for the last-focused window in the stack becomes 50% opaque, the rest transparent)

Thanks for reminding me that I should add a feature flag for the `stackInactive` functionality so that folks can disable it.
That was much more difficult to get this working than I expected; I only included it out of stubbornness.  What's worse, there's a hammerspoon bug (https://github.com/Hammerspoon/hammerspoon/issues/2400) that makes it very difficult to detect changes in focus when switching between windows of the same app. If you've seen bugs where multiple indicators will take on 100% opacity, or fail to fade when the stack is unfocused, or fail to un-fade when the stack is focused … it's b/c of the contortions required just to detect something basic like "focus changed" in these edge-cases. 

---

Apologies for the length. I'll take a look at #43 now. And please don't hesitate to share more problems / ideas / suggestions :-)

**Comment by alextremblay** [comment] 2020-10-06 02:16
Awesome! Thank you so much for the detailed reply. I'll definitely check out the configuration branch when I have some time to play around with it

**Comment by AdamWagner** [comment] 2020-10-10 20:14
@alextremblay You bet, thanks for the detailed report(s). Fuzzy frame detection and improved configuration are now available on master. 

Note that the update requires Stackline to be initialized in your `~/.hammerspoon/init.lua` file:

**init.lua before**

```lua
stackline = require "stackline.stackline.stackline"
stackline:init()
``

**Comment by AdamWagner** [comment] 2020-11-29 04:13
@alextremblay BTW, the fuzzy frame detection has been merged into master for a while now, so all you'd need to do is update `stackline`:

```sh
cd ~/.hammerspoon/stackline && git pull
```

If you haven't updated in a while, be sure to check out [this post with upgrade instructions](https://github.com/AdamWagner/stackline/issues/33#issuecomment-706604283). 

Also, I've found that a `fuzzFactor` value of around `90` is best if you want to make sure that stacked iTerm2 windows are reliably detected. You can set this by overriding the default config (`30`) during initialization:

```lua
-- in your ~/.hammerspoon/init.lua file
stackline = require "stackline.stackline.stackline"
local stacklineConfig = {
    features = {
        fzyFrameDetect = {
            enabled = true,
            fuzzFactor = 30
        },
    },
}
stackline:init(stacklineConfig)
```

**Closed** 2020-11-29 04:15 UTC
Labels: bug, enhancement

**Comment by alextremblay** [comment] 2020-12-08 14:11
Thank you!

**Comment by siematypie** [comment] 2023-03-02 22:37
I have the same issue with alacritty only, first instance shows up but every additional shows up as a blank icon, `fuzzy` is not helping :(
